# Generated by Django 4.2.20 on 2025-09-02 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
        ('allusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(default=601, on_delete=django.db.models.deletion.CASCADE, to='room.room'),
        ),
    ]
