# Generated by Django 4.2.20 on 2025-09-09 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0002_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='PhoneNumber',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d+$', 'این فیلد فقط باید شامل عدد 10 رقمی باشد')]),
        ),
    ]
