# Generated by Django 4.2.20 on 2025-09-09 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allusers', '0003_alter_customuser_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='PhoneNumber',
            new_name='phonenumber',
        ),
    ]
