# Generated by Django 4.2.20 on 2025-09-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rooms', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unset')], default='U', max_length=1)),
            ],
        ),
    ]
