# Generated by Django 4.2.20 on 2025-09-27 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_alter_requests_updated_at'),
        ('logs', '0003_remove_logs_message_logs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.requests'),
        ),
    ]
