# Generated by Django 4.2.20 on 2025-09-07 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allusers', '0002_student_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_type', models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdraw'), ('U', 'Unset')], default='U', max_length=1)),
                ('t_status', models.CharField(choices=[('C', 'Complete'), ('F', 'Failed'), ('P', 'Pending'), ('U', 'Unset')], default='U', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_id', models.CharField(max_length=8, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allusers.student')),
            ],
        ),
    ]
