# Generated by Django 4.2.20 on 2025-09-13 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allusers', '0004_rename_phonenumber_customuser_phonenumber'),
        ('room', '0002_room_is_full_room_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('R', 'rejected'), ('A', 'accepted'), ('P', 'pending'), ('U', 'unsent')], default='U', max_length=1)),
                ('is_priorty', models.BooleanField(default=False)),
                ('r_type', models.CharField(choices=[('R', 'repairs'), ('C', 'cleaning'), ('CT', 'complaint'), ('RE', 'requiredequipment'), ('U', 'unset')], default='U', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allusers.student')),
            ],
        ),
    ]
