# Generated by Django 4.2.20 on 2025-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='status',
            field=models.CharField(choices=[('R', 'rejected'), ('A', 'accepted'), ('P', 'pending'), ('U', 'unsent')], default='P', max_length=1),
        ),
    ]
