# Generated by Django 4.2.20 on 2025-09-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_alter_requests_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
