# Generated by Django 4.2.20 on 2025-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_alter_requests_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
