# Generated by Django 4.2.20 on 2025-09-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='amount',
        ),
        migrations.AddField(
            model_name='logs',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
