# Generated by Django 4.2.20 on 2025-09-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_remove_logs_amount_logs_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='message',
        ),
        migrations.AddField(
            model_name='logs',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
